project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: AEMeR
    right:
      - href: index.qmd
        text: "![](img/logos.png){height=1in}"

language: es

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

